wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1663060405
    t:
      1:
      - 1
      - 12
      2:
      - 1
      - 12
      3:
      - 13
      4: 3.9.13
      5: 0.12.4
      8:
      - 5
