wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1663217599
    t:
      1:
      - 1
      - 12
      2:
      - 1
      - 12
      3:
      - 13
      4: 3.9.13
      5: 0.12.4
      8:
      - 5
batch_size:
  desc: null
  value: 64
constraint:
  desc: null
  value: none
early_stop_patience:
  desc: null
  value: 4
h_size:
  desc: null
  value: 32
hop_size:
  desc: null
  value: 512
input_transform:
  desc: null
  value: log1p
is_real:
  desc: null
  value: true
lam_1:
  desc: null
  value: 0.01
n_devices:
  desc: null
  value: 2
n_frames:
  desc: null
  value: 1
n_in_chan:
  desc: null
  value: 1
n_layers:
  desc: null
  value: 2
n_out_chan:
  desc: null
  value: 1
name:
  desc: null
  value: meta_eq_none_16_c
pad_size:
  desc: null
  value: 0
reduce_lr_patience:
  desc: null
  value: 1
total_epochs:
  desc: null
  value: 1000
unroll:
  desc: null
  value: 16
val_period:
  desc: null
  value: 10
window_size:
  desc: null
  value: 1024
